name: Helm Scan

on:
  schedule:
    - cron: 7 0 * * *
  push:
    branches: ["main"]
    paths: ["charts/test-service"]
  pull_request:
    branches: ["main"]
    paths: ["charts/test-service"]

jobs:
  HelmScan:
    runs-on: [self-hosted, mgmt-eks]
    steps:
    - uses: xometry/the-forge/helm-scan-and-publish@helm-scan-and-publish-v1
      with:
        chart_path: charts/test-service
        helm_repo_url: https://helm-charts.ci.dev.xometry.net
        version: none
        scan_only: true
        repository: test-service
        tag: ${{ github.sha }}
